# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- main
variables:
- name: agent.preferpowershelloncontainers
  value: 'True'
pool:
  vmImage: 'windows-latest'
container:
  image: uipathrobot3.azurecr.io/aawasthiiuipath:4
  endpoint: uipathrobot3

steps:
- script: C:\UiPath\UiRobot.exe pack $(Build.SourcesDirectory)\project.json -o $(Build.ArtifactStagingDirectory)\ -v 1.0.$(Build.BuildNumber)
  displayName: 'Build Artifacts'
- publish: $(Build.ArtifactStagingDirectory)
  artifact: drop
- powershell:
    Import-Module Uipath.Powershell
    $token = Get-UiPathAuthToken -ClientId $(uatClientId) -AccountName $(uatAccountName) -TenantName $(uatTenantName) -UserKey $(uatUserKey) -CloudDeployment 'prod' 
    Add-UiPathPackage -PackageFile $(Build.ArtifactStagingDirectory)\HelloWorld.$(Build.BuildNumber).nupkg -AuthToken $token